### ISSUE TITLE
Error whicle building package

### ISSUE THREAD

**Issue by nagamanikandank** [PredixDev/asset-bootstrap#1]
I did 

`mvn clean package`

 and faced the following error

`[ERROR] Failed to execute goal on project asset-bootstrap-client: Could not resolve dependencies for project com.ge.predix.solsvc:asset-bootstrap-client:jar:1.2.8: The following artifacts could not be resolved: 
com.ge.predix.solsvc:predix-rest-client:jar:1.2.8, 
com.ge.predix.solsvc:ext-model:jar:1.7.9, 
com.ge.predix.solsvc:ext-util:jar:1.7.9: 
Failure to find com.ge.predix.solsvc:predix-rest-client:jar:1.2.8 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by turnerth** [comment]
try to delete ~/.m2/repository/com/ge/predix and retry.

**Comment by nagamanikandank** [comment]
@turnerth  , still same error . This is the repo I am using in my maven settings

```
<repository>
            <id>artifactory.repo</id>
            <name>artifactory.repo or name of your choosing</name>
            <url>https://devcloud.swcoe.ge.com/artifactory/repo</url>
    </repository>
    <repository>
            <id>artifactory.external</id>
            <name>artifactory.external or name of your choosing.</name>
            <url>https://artifactory.predix.io/artifactory/repo</url>
</repository>
```
